---

- name: run the playbook tasks on the localhost from the ~/samuraiwtf folder
  hosts: 127.0.0.1
  connection: local
  tasks:
### Prerequisites
  - name: ensure prerequisite packages are installed
    yum:
      name:
        - python3
    become: true

  - name: python prerequisite modules
    pip:
      name: "{{ modules }}"
      executable: /usr/bin/pip3
    become: yes
    vars:
      modules:
      - ansible