- name: Customizations for the samurai user.
  hosts: all
  connection: local
  become: true
  tasks:

  - name: Copy home folder contents
    copy:
      dest: /home/samurai
      src: ../config/home/
      owner: samurai

  # - name: Setup file to run on startup
  #   copy:
  #     dest: /etc/rc.local
  #     content: |
  #       #!/bin/sh -e
  #       /opt/samurai/set_background.sh || exit 1

  #       exit 0
  #     mode: 0755